# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: hamleb/wolfcms:mysql_wolf
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root

  web:
    image: hamleb/wolfcms:wolf
    links:
      - db
    ports:
      - 9999:80
    